from typing import Any, Callable

class JSException(Exception): ...

class Context:
    def eval(self, code: str) -> Any: ...
    def set(self, name: str, value: Any) -> None: ...
    def get(self, name: str) -> Any: ...
    def add_callable(self, name: str, fn: Callable[..., Any]) -> None: ...
    def parse_json(self, json_str: str) -> Any: ...
    def set_time_limit(self, seconds: float) -> None: ...
    def set_memory_limit(self, limit: int) -> None: ...
    def set_max_stack_size(self, limit: int) -> None: ...
    def gc(self) -> None: ...
